spring:
  main:
    banner-mode: off
  security:
    user:
      name: admin
      password: pwd

logging:
  level:
    org:
      springframework:
        security: DEBUG
server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:  http://admin:pwd@localhost:8761/eureka/
  server:
    enable-self-preservation: true
    renewalPercentThreshold: 0.20